### ISSUE TITLE
Affiliations

### ISSUE THREAD

**Issue by lrsantos11** [lpoo/perprof-jors#13]
I can't find our affiliations on the final PDF.
BTW, should we mention our new affiliation @abelsiqueira?

**Comment by abelsiqueira** [comment]
I'm still looking how to make it appear.
Yes, we must.

**Comment by abelsiqueira** [comment]
Implemented in abelsiqueira@bac4fe6.
@lrsantos11 and @r-gaia-cs, which, if any, e-mails do you want there?

**Comment by r-gaia-cs** [comment]
raniere@ime.unicamp.br

**Comment by lrsantos11** [comment]
Updated on lrsantos11@9e9cd5d
